version: '3.1'

services:
  api:
    image: daniel10510/student-api:1
    deploy:
      replicas: 1
    networks:
      - api-tier
    ports:
      - 8912:5000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: superootpassword

  frontend:
    image: daniel10510/student-frontend:1
    deploy:
      replicas: 1
    networks:
      - api-tier
    ports:
      - 8089:80

  db:
    image: postgres:9.6.16-alpine
    deploy:
      replicas: 1
    networks:
      - api-tier
    ports:
      - 7789:5432
    environment:
      POSTGRES_PASSWORD: superootpassword

networks:
  api-tier: